# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v3
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Execute Gradle Build
      run: ./gradlew clean build
    - uses: actions/upload-artifact@v4
      name: Upload artifact
      with:
        name: ConsoleReader
        path: build/libs/*.jar
